### ISSUE TITLE
The ICE40 FPGA (iCE40LP1K-CM49) calibration file is missing

### ISSUE THREAD

**Issue by 3sUser** [Mi-Thorium/android_device_xiaomi_Mi8937#9]
People have a problem with the battery and, for example, turning off the smartphone under heavy load (when, for example, the battery still has 40%).
And all because of the lack of the ice40.bin calibration file (in system/etc/firmware). Which is used by ICE40 FPGA in many Redmi devices, e.g. Redmi 3S, Redmi 7A, Redmi 7.

You can read, for example, here what the ICE40 system is responsible for.

https://android.googlesource.com/kernel/msm/+/android-msm-bullhead-3.10-marshmallow-dr/Documentation/usb/ice40-hcd.txt

This applies to all your custom roms.

**Comment by me-cafebabe** [comment]
point it out, which piece of code actually wants to load this firmware in the kernel?

also, is system/etc/firmware still being used nowadays?
